[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "http://night.nightsidecode.co/*"
  to = "https://www.mel-24.com/:splat"
  status = 301
  force = true


[[redirects]]
  from = "https://night.nightsidecode.co/*"
  to = "https://www.mel-24.com/:splat"
  status = 301
  force = true



