#[[redirects]]
#from = "/search"
#to = "https://google.com/search?q=stuff"
#status = 200
#proxy = true
#pattern = "^/proxy(?:|/|(.*)/?)$"

[[redirects]]
from = "/*"
to = "https://epic-goldstine-54d029.netlify.app"
status = 200
