# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200


[[redirects]]
from = "/search"
to = "https://google.com/search?q=stuff"
status = 200
proxy = true
pattern = "^/proxy(?:|/|(.*)/?)$"